### ISSUE TITLE
Erorr installing landsat-util on Mac

### ISSUE THREAD

**Issue by mabdelrazek** [developmentseed/landsat-util#117]
I am trying to install landsat-util on MacBook pro, Yosmite MacOS 10.10.3, but getting a warning and several errors (I also tried sudo -H and chmod 777 /Users/X/Library/Caches/pip/http and parent directories up to Caches, but it didn't work

X$ sudo pip install landsat-util

The directory '/Users/X/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
You are using pip version 7.1.0, however version 7.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
The directory '/Users/X/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 223, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/pip/commands/install.py", line 293, in run
    wb.build(autobuilding=True)
  File "/usr/local/lib/python2.7/site-packages/pip/wheel.py", line 705, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 334, in prepare_files
    functools.partial(self._prepare_file, finder))
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 321, in _walk_req_to_install
    more_reqs = handler(req_to_install)
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 409, in _prepare_file
    req_to_install, finder)
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 355, in _check_skip_installed
    req_to_install.check_if_exists()
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 981, in check_if_exists
    self.req.project_name
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 545, in get_distribution
    dist = get_provider(dist)
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 425, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 946, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 838, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
ContextualVersionConflict: (homura 0.1.0 (/usr/local/lib/python2.7/site-packages), Requirement.parse('homura>=0.1.1'), set(['landsat-util']))

best,
mohammad

**Comment by mabdelrazek** [comment]
Updating pip solved the problem
sudo -H pip install --upgrade pip

But now "landsat" command gives the following error: 

Traceback (most recent call last):
  File "/usr/local/bin/landsat", line 5, in <module>
    import landsat.landsat
  File "/usr/local/lib/python2.7/site-packages/landsat/landsat.py", line 13, in <module>
    import pycurl
ImportError: pycurl: libcurl link-time version (7.37.1) is older than compile-time version (7.43.0)

curl 7.43.0 for Mac is only available via brew, but it didn't work, still getting the same error

**Comment by stml** [comment]
I had a lot of trouble installing - ultimately, all were solved by installing and running within a virtual environment: http://docs.python-guide.org/en/latest/dev/virtualenvs/

**Comment by scisco** [comment]
@mabdelrazek This is mainly an issue with your pycurl installation. What @stml suggested is probably the best way to get a clean install. Did you have any luck with setting up a virtualenv?
