### ISSUE TITLE
NDVI not working in 0.9.1

### ISSUE THREAD

**Issue by gmaclennan** [developmentseed/landsat-util#127]
When I run `landsat process --ndvi --clip=-77.5,-1.5,-77,-1 LC80090612015251LGN00.tar.bz` I get the following error with 0.9.1 installed from pip, but running the latest develop branch does work. However, `--ndvigrey` in the develop branch creates the same (colored) output as `--ndvi` in the develop branch.

```
Traceback (most recent call last):
  File "/usr/local/bin/landsat", line 8, in <module>
    landsat.landsat.__main__()
  File "/usr/local/lib/python2.7/site-packages/landsat/landsat.py", line 435, in __main__
    exit(*main(args))
  File "/usr/local/lib/python2.7/site-packages/landsat/landsat.py", line 275, in main
    args.ndvigrey, bounds)
  File "/usr/local/lib/python2.7/site-packages/landsat/landsat.py", line 426, in process_image
    return p.run()
  File "/usr/local/lib/python2.7/site-packages/landsat/decorators.py", line 10, in wrapped_f
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/landsat/ndvi.py", line 75, in run
    return self.write_band(output_band, output_file, image_data)
  File "/usr/local/lib/python2.7/site-packages/landsat/ndvi.py", line 112, in write_band
    rgb_bands.append(v_manual_colormap(output_band, i))
  File "/usr/local/lib/python2.7/site-packages/numpy/lib/function_base.py", line 1811, in __call__
    return self._vectorize_call(func=func, args=vargs)
  File "/usr/local/lib/python2.7/site-packages/numpy/lib/function_base.py", line 1880, in _vectorize_call
    outputs = ufunc(*inputs)
  File "/usr/local/lib/python2.7/site-packages/landsat/ndvi.py", line 100, in manual_colormap
    return self.cmap[n][i]
KeyError: 191
```

**Comment by akudrya** [comment]
Hi @scisco, similar issue even without clipping. Looks like "Apply color map" cause errors. When I did ```--ndvigrey``` everything worked fine

```
Traceback (most recent call last):
  File "/usr/local/bin/landsat", line 8, in <module>
    landsat.landsat.__main__()
  File "/Library/Python/2.7/site-packages/landsat/landsat.py", line 435, in __main__
    exit(*main(args))
  File "/Library/Python/2.7/site-packages/landsat/landsat.py", line 275, in main
    args.ndvigrey, bounds)
  File "/Library/Python/2.7/site-packages/landsat/landsat.py", line 426, in process_image
    return p.run()
  File "/Library/Python/2.7/site-packages/landsat/decorators.py", line 10, in wrapped_f
    return func(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/landsat/ndvi.py", line 75, in run
    return self.write_band(output_band, output_file, image_data)
  File "/Library/Python/2.7/site-packages/landsat/ndvi.py", line 112, in write_band
    rgb_bands.append(v_manual_colormap(output_band, i))
  File "/Library/Python/2.7/site-packages/numpy-override/numpy/lib/function_base.py", line 1572, in __call__
    return self._vectorize_call(func=func, args=vargs)
  File "/Library/Python/2.7/site-packages/numpy-override/numpy/lib/function_base.py", line 1638, in _vectorize_call
    outputs = ufunc(*inputs)
  File "/Library/Python/2.7/site-packages/landsat/ndvi.py", line 100, in manual_colormap
    return self.cmap[n][i]
KeyError: 122
```

And I also had ```KeyError: 85``` with another image.

**Comment by scisco** [comment]
@akudrya @gmaclennan yes. this is a bug. Will issue a hotfix shortly.

**Comment by akudrya** [comment]
@scisco Thanks! Looking forward to get it
