### ISSUE TITLE
landsat-util install

### ISSUE THREAD

**Issue by MarinJane** [developmentseed/landsat-util#138]
Can't seem to get past this error when following install instructions and initiating the program. This program was working for me several months ago, but I figured the update would be good since it'd been awhile. Not sure what went wrong. Also trying to initiate in a virtualenv but still getting the same error. I thought it had something to do with my numpy version, but with the virutalenv it shouldn't be an issue.

$ landsat
Traceback (most recent call last):
  File "/usr/local/bin/landsat", line 5, in <module>
    import landsat.landsat
  File "/usr/local/lib/python2.7/site-packages/landsat/landsat.py", line 23, in <module>
    from image import Simple, PanSharpen, FileDoesNotExist
  File "/usr/local/lib/python2.7/site-packages/landsat/image.py", line 16, in <module>
    from rasterio.warp import reproject, RESAMPLING, transform, transform_bounds
  File "/usr/local/lib/python2.7/site-packages/rasterio/warp.py", line 8, in <module>
    from rasterio._warp import _transform_geom, _reproject, RESAMPLING
  File "__init__.pxd", line 155, in init rasterio._warp (rasterio/_warp.cpp:23940)
ValueError: numpy.dtype has the wrong size, try recompiling

**Comment by sr0805** [comment]
Apparently I am getting a similar kind of error. Though this is my first time installation. Can't figure out what is going wrong and where.

$ landsat -h
Traceback (most recent call last):
  File "/home/usr/anaconda2/bin/landsat", line 5, in <module>
    import landsat.landsat
  File "/home/usr/anaconda2/lib/python2.7/site-packages/landsat/landsat.py", line 23, in <module>
    from image import Simple, PanSharpen, FileDoesNotExist
  File "/home/usr/anaconda2/lib/python2.7/site-packages/landsat/image.py", line 15, in <module>
    from rasterio.coords import disjoint_bounds
ImportError: cannot import name disjoint_bounds

**Comment by sr0805** [comment]
Upgraded rasterio, that removed "ImportError: cannot import name disjoint_bounds" , but still cant figure out the following errors:

Traceback (most recent call last):
  File "/home/sr0805/anaconda2/bin/landsat", line 5, in <module>
    import landsat.landsat
  File "/home/sr0805/anaconda2/lib/python2.7/site-packages/landsat/landsat.py", line 23, in <module>
    from image import Simple, PanSharpen, FileDoesNotExist
  File "/home/sr0805/anaconda2/lib/python2.7/site-packages/landsat/image.py", line 13, in <module>
    import numpy
  File "/home/sr0805/anaconda2/lib/python2.7/site-packages/numpy/__init__.py", line 180, in <module>
    from . import add_newdocs
  File "/home/sr0805/anaconda2/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/home/sr0805/anaconda2/lib/python2.7/site-packages/numpy/lib/__init__.py", line 18, in <module>
    from .polynomial import *
  File "/home/sr0805/anaconda2/lib/python2.7/site-packages/numpy/lib/polynomial.py", line 20, in <module>
    from numpy.linalg import eigvals, lstsq, inv
  File "/home/sr0805/anaconda2/lib/python2.7/site-packages/numpy/linalg/__init__.py", line 51, in <module>
    from .linalg import *
  File "/home/sr0805/anaconda2/lib/python2.7/site-packages/numpy/linalg/linalg.py", line 29, in <module>
    from numpy.linalg import lapack_lite, _umath_linalg
ImportError: /usr/lib/liblapack.so.3: undefined symbol: gotoblas

**Comment by lolob** [comment]
Try to follow these steps: It works for me and I use Mac OSX El Capitan.

1. Install virtualenv
pip install virtualenv virtualenvwrapper

1. Setup virtualenvwrapper in ~/.bash_profile. Add these lines (nano editor )to your ~/.bash_profile:

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
cp ~/.bash_profile ~/.bash_profile-org
printf '\n%s\n%s\n%s' '# virtualenv' 'export WORKON_HOME=~/virtualenvs' \
'source /usr/local/bin/virtualenvwrapper.sh' >> ~/.bash_profile

2. Enable the environment.From terminal enter:

source ~/.bash_profile
mkdir -p $WORKON_HOME
mkvirtualenv landsat8

3. Install landsat-util. First upgrade pip.
pip install --upgrade pip
pip install --upgrade landsat-util

4. Thats all. From terminal enter 'landsat -h'.
