### ISSUE TITLE
ValueError: numpy.dtype has the wrong size, try recompiling

### ISSUE THREAD

**Issue by planemad** [developmentseed/landsat-util#177]
On OSX, installed using `sudo pip install landsat-util`. This is what I get:

```
$ landsat -h
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/landsat", line 5, in <module>
    import landsat.landsat
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/landsat/landsat.py", line 29, in <module>
    from .image import Simple, PanSharpen, FileDoesNotExist
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/landsat/image.py", line 18, in <module>
    from rasterio.warp import reproject, RESAMPLING, transform, transform_bounds
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/rasterio/warp.py", line 14, in <module>
    from rasterio._warp import (_transform_geom, _reproject, Resampling,
  File "__init__.pxd", line 155, in init rasterio._warp (rasterio/_warp.cpp:25188)
ValueError: numpy.dtype has the wrong size, try recompiling
```

Browsing around, I found i might need to reinstall pandas, but it does not fix the issue. I'm able to import all the python dependencies without issues:

```
>>> import pandas
>>> import numpy
>>> import landsat
>>> import rasterio
```

**Comment by planemad** [comment]
Related https://github.com/developmentseed/landsat-util/issues/138

**Comment by sgillies** [comment]
@planemad looks like you need to upgrade numpy. The Rasterio wheels I've made for OS X require at least 1.10. Also, I'm afraid to see you `sudo pip install` Rasterio because I can't guarantee that it won't upgrade your site-packages without affecting other installed programs :fearful: Better to use a virtualenv for landsat-util related work.

**Comment by planemad** [comment]
@sgillies works! :+1:
