### ISSUE TITLE
Problem with landsat process

### ISSUE THREAD

**Issue by AlmuHS** [developmentseed/landsat-util#196]
I have installed landsat-util in Gentoo from pip install.
The _landsat download_ run correctly, but when I try to process the images with landsat process, it shows that errors: https://bpaste.net/show/4c07c5dfc14a

===> Image processing started for bands 4-3-2
===> Getting boundaries
===> Projecting
     band 4
Time spent : 3.26 seconds
Traceback (most recent call last):
  File "/usr/bin/landsat", line 4, in <module>
    __import__('pkg_resources').run_script('landsat-util==0.13.0', 'landsat')
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 1652, in run_script
    exec(code, namespace, namespace)
  File "/usr/lib64/python2.7/site-packages/landsat_util-0.13.0-py2.7.egg/EGG-INFO/scripts/landsat", line 8, in <module>
    landsat.landsat.__main__()
  File "/usr/lib64/python2.7/site-packages/landsat_util-0.13.0-py2.7.egg/landsat/landsat.py", line 491, in __main__
    exit(*main(args))
  File "/usr/lib64/python2.7/site-packages/landsat_util-0.13.0-py2.7.egg/landsat/landsat.py", line 306, in main
    args.ndvigrey, bounds)
  File "/usr/lib64/python2.7/site-packages/landsat_util-0.13.0-py2.7.egg/landsat/landsat.py", line 479, in process_image
    return p.run()
  File "/usr/lib64/python2.7/site-packages/landsat_util-0.13.0-py2.7.egg/landsat/decorators.py", line 11, in wrapped_f
    return func(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/landsat_util-0.13.0-py2.7.egg/landsat/image.py", line 408, in run
    self._warp(image_data, bands, new_bands)
  File "/usr/lib64/python2.7/site-packages/landsat_util-0.13.0-py2.7.egg/landsat/image.py", line 159, in _warp
    num_threads=2)
  File "/usr/lib64/python2.7/site-packages/rasterio-0.32.0-py2.7-linux-x86_64.egg/rasterio/warp.py", line 244, in reproject
    **kwargs)
  File "rasterio/_warp.pyx", line 487, in rasterio._warp._reproject (rasterio/_warp.cpp:8337)
  File "rasterio/_err.pyx", line 70, in rasterio._err.GDALErrCtxManager.__exit__ (rasterio/_err.c:994)
RuntimeError: CPLCreateJoinableThread() failed in ChunkAndWarpMulti()

I have other version installed from main sources, but shows the same problem.
Can you help me?

**Comment by AlmuHS** [comment]
I have just update gdal to 2.0.2 version, and now there are other error in download command
https://bpaste.net/show/606ad9f28eb8

**Comment by AlmuHS** [comment]
I set a symbolic link called libgdal.so.1, and the download process has solved.
But the process problem continues

https://bpaste.net/show/3efb1f1e7f49

**Comment by AlmuHS** [comment]
Solved: I added --with-threads=yes in the ebuild
https://bpaste.net/show/a60bad593a79
