### ISSUE TITLE
Requirement polyline==1.1 seems to be broken in python3

### ISSUE THREAD

**Issue by vesnikos** [developmentseed/landsat-util#201]
using ve and python3 (ubuntu 16.04) :

```
(ve) root@575f07e14ab5:~/ve# pip install polyline==1.1 -U
Collecting polyline==1.1
  Using cached polyline-1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-pfbud48l/polyline/setup.py", line 15, in <module>
        long_desc = f.read()
      File "/root/ve/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 662: ordinal not in range(128)
```

Consequently installing landsat-util from pip fails as well.
Newer version seems to be ok. I recommend upgrading the requirement  from 1.1 to 1.3

**Comment by drewbo** [comment]
Bumped `polyline` to `1.3` (there was a `six` mismatch, among other things) as part of #217
