### ISSUE TITLE
errors Pansharpen landsat 8

### ISSUE THREAD

**Issue by lequynhhoa** [developmentseed/landsat-util#204]
Dear all,
I am pansharpening but I got error as the below. Please tell me how to fix it.
I can't pansharpen :(.

root@osgeolive:/home/user# landsat process /root/landsat/downloads/LC81260452014284LGN00 --pansharpen===> PanSharpened Image processing started for bands 4-3-2-8
===> Getting boundaries
===> Rescaling
     band 4
Time spent : 103.93 seconds
Traceback (most recent call last):
  File "/usr/local/bin/landsat", line 8, in <module>
    landsat.landsat.__main__()
  File "/usr/local/lib/python2.7/dist-packages/landsat/landsat.py", line 491, in __main__
    exit(*main(args))
  File "/usr/local/lib/python2.7/dist-packages/landsat/landsat.py", line 306, in main
    args.ndvigrey, bounds)
  File "/usr/local/lib/python2.7/dist-packages/landsat/landsat.py", line 479, in process_image
    return p.run()
  File "/usr/local/lib/python2.7/dist-packages/landsat/decorators.py", line 11, in wrapped_f
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/landsat/image.py", line 456, in run
    bands[:3] = self._rescale(bands[:3])
  File "/usr/local/lib/python2.7/dist-packages/landsat/image.py", line 526, in _rescale
    bands[key] = sktransform.rescale(band, 2)
  File "/usr/local/lib/python2.7/dist-packages/skimage/transform/_warps.py", line 188, in rescale
    clip=clip, preserve_range=preserve_range)
  File "/usr/local/lib/python2.7/dist-packages/skimage/transform/_warps.py", line 119, in resize
    preserve_range=preserve_range)
  File "/usr/local/lib/python2.7/dist-packages/skimage/transform/_geometric.py", line 1343, in warp
    order=order, mode=mode, cval=cval)
  File "skimage/transform/_warps_cy.pyx", line 106, in skimage.transform._warps_cy._warp_fast (skimage/transform/_warps_cy.c:2530)
MemoryError
root@osgeolive:/home/user#

**Comment by cmdelatorre** [comment]
I'm no expert and I'm not even sure, but apparently you're running out of memory. ¿is it possible?. Check the RAM use while running the script

**Comment by aornugent** [comment]
I have the same error with 4GB RAM. Could someone please give an indication of the memory requirements for pansharpening?
