### ISSUE TITLE
SSL certificate verify failure

### ISSUE THREAD

**Issue by bucricket** [developmentseed/landsat-util#225]
Hi all,

I get the following error now when searching....

landsat search --cloud 4 --start "january 1 2014" --end "january 10 2014" -p 009,045

Traceback (most recent call last):
  File "/Applications/anaconda/bin/landsat", line 11, in <module>
    sys.exit(__main__())
  File "/Applications/anaconda/lib/python2.7/site-packages/landsat/landsat.py", line 488, in __main__
    print(main(args))
  File "/Applications/anaconda/lib/python2.7/site-packages/landsat/landsat.py", line 357, in main
    geojson=args.geojson)
  File "/Applications/anaconda/lib/python2.7/site-packages/landsat/search.py", line 96, in search
    r = requests.get('%s?search=%s&limit=%s' % (self.api_url, search_string, limit))
  File "/Applications/anaconda/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/Applications/anaconda/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/Applications/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/Applications/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/Applications/anaconda/lib/python2.7/site-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

**Comment by MarinJane** [comment]
I too am getting this error as well today.

landsat search --cloud 50 -p "001,114"
Traceback (most recent call last):
  File "/projects/makl5454/venv/bin/landsat", line 11, in <module>
    sys.exit(__main__())
  File "/projects/makl5454/venv/lib/python2.7/site-packages/landsat/landsat.py", line 488, in __main__
    print(main(args))
  File "/projects/makl5454/venv/lib/python2.7/site-packages/landsat/landsat.py", line 357, in main
    geojson=args.geojson)
  File "/projects/makl5454/venv/lib/python2.7/site-packages/landsat/search.py", line 96, in search
    r = requests.get('%s?search=%s&limit=%s' % (self.api_url, search_string, limit))
  File "/projects/makl5454/venv/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/projects/makl5454/venv/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/projects/makl5454/venv/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/projects/makl5454/venv/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/projects/makl5454/venv/lib/python2.7/site-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
landsat --version
landsat version 0.13.1

**Comment by scisco** [comment]
I made an update to our SSL cert deployment. Could you try again and let me know if you still get this error?

@MarinJane @bucricket

**Comment by MarinJane** [comment]
It appears to be working now. Thank you!

**Comment by scisco** [comment]
Great! happy to help.
