### ISSUE TITLE
Problems with search

### ISSUE THREAD

**Issue by ivanhigueram** [developmentseed/landsat-util#232]
Hello! 

I've been trying to search some L8 images using `landsat-util`. I run the examples on the documentation:

`$:  landsat search --lat 38.9004204 --lon -77.0237117`

But after a few seconds the command raises the following error:

```
Traceback (most recent call last):
  File "/Users/ivan/anaconda3/envs/landsat-util/bin/landsat", line 11, in <module>
    sys.exit(__main__())
  File "/Users/ivan/anaconda3/envs/landsat-util/lib/python3.5/site-packages/landsat/landsat.py", line 488, in __main__
    print(main(args))
  File "/Users/ivan/anaconda3/envs/landsat-util/lib/python3.5/site-packages/landsat/landsat.py", line 357, in main
    geojson=args.geojson)
  File "/Users/ivan/anaconda3/envs/landsat-util/lib/python3.5/site-packages/landsat/search.py", line 98, in search
    r_dict = json.loads(r.text)
  File "/Users/ivan/anaconda3/envs/landsat-util/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/Users/ivan/anaconda3/envs/landsat-util/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/ivan/anaconda3/envs/landsat-util/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
``` 

I have used different machines (AWS Ubuntu instance and a Mac box), but the result is the same for both. I have installed the `landsat-util` utility in a virtual environment with `Python=3.5` and with the requirements of the package. I am doing anything wrong? I've update the `geojson` library, but the errors persists. 

Thank you so much.

**Comment by neeraj9194** [comment]
I think the development seed's API is down... [see here](https://api.developmentseed.org/satellites/landsat).

**Comment by drewbo** [comment]
Should be back up now, thanks for the feedback @neeraj9194 @ivanhigueram
