### ISSUE TITLE
Search ConnectionError

### ISSUE THREAD

**Issue by rahimramezanian** [developmentseed/landsat-util#243]
I use docker, Download instruction works but search produce an error

`$ docker run -it -v ~/landsat:/root/landsat developmentseed/landsat-util:latest landsat search --cloud 4 --start "january 1 2014" --end "january 10 2014" -p 009,045`

The response is

`Traceback (most recent call last):
  File "/usr/local/bin/landsat", line 9, in <module>
    load_entry_point('landsat-util==0.13.1', 'console_scripts', 'landsat')()
  File "/landsat/landsat/landsat.py", line 488, in __main__
    print(main(args))
  File "/landsat/landsat/landsat.py", line 357, in main
    geojson=args.geojson)
  File "/landsat/landsat/search.py", line 96, in search
    r = requests.get('%s?search=%s&limit=%s' % (self.api_url, search_string, limit))
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))`

Thanks.

**Comment by leoromanovsky** [comment]
Did you get it to work?

**Comment by matthewhanson** [comment]
Unable to reproduce, please reopen if this continues to be a problem.
