### ISSUE TITLE
Docker search SSL error

### ISSUE THREAD

**Issue by palewire** [developmentseed/landsat-util#260]
```
$ sudo docker run -it -v ~/landsat:/root/landsat developmentseed/landsat-util:latest landsat search --lat 33.9436973 --lon -118.4073388       
```
```   
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Traceback (most recent call last):
  File "/usr/local/bin/landsat", line 9, in <module>
    load_entry_point('landsat-util==0.13.1', 'console_scripts', 'landsat')()
  File "/landsat/landsat/landsat.py", line 488, in __main__
    print(main(args))
  File "/landsat/landsat/landsat.py", line 357, in main
    geojson=args.geojson)
  File "/landsat/landsat/search.py", line 96, in search
    r = requests.get('%s?search=%s&limit=%s' % (self.api_url, search_string, limit))
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
```

**Comment by ninexy** [comment]
i had the same error. can you fit it? please help!

**Comment by pravent** [comment]
same for me

**Comment by pravent** [comment]
that seems unmaintained, it uses python 2.7. Many modern TLS/SSL features are not available in older versions of Python, so it's recommended to upgrade to at least Python 3.6 or higher

**Comment by pravent** [comment]
ah! it turns out this will work with the docker image with tag **dev**. see:
```
$  docker run -it -v ~/landsat:/root/landsat developmentseed/landsat-util:dev landsat search --cloud 4 --start "january 1 2014" --end "january 10 2014" -p 009,045
===> 1 items were found
{
    "limit": 10,
    "results": [
        {
            "cloud": 3.27,
            "date": "2014-01-08",
            "path": "009",
            "row": "045",
            "sat_type": "L8",
            "sceneID": "LC80090452014008LGN02",
            "thumbnail": "https://earthexplorer.usgs.gov/browse/landsat_8/2014/009/045/LC08_L1TP_009045_20140108_20180130_01_T1.jpg"
        }
    ],
    "status": "SUCCESS",
    "total": 1,
    "total_returned": 1
}
['Search completed!']
```
