### ISSUE TITLE
can not find gdal-config

### ISSUE THREAD

**Issue by koustubhavachat** [developmentseed/landsat-util#42]
C:\Python27\landsat-util-master>python setup.py install
Traceback (most recent call last):
  File "setup.py", line 20, in <module>
    if subprocess.call(['which', 'gdal-config']):
  File "C:\Python27\lib\subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "C:\Python27\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

**Comment by jacquestardie** [comment]
try running `gdal-config --version` in a terminal and see if you get any output
