### ISSUE TITLE
Having the same issues as someone else; failure with Rasterio/Gdal

### ISSUE THREAD

**Issue by petulla** [developmentseed/landsat-util#99]
Output of any command line utils:

```Traceback (most recent call last):
  File "/Users/sam/anaconda/bin/landsat", line 5, in <module>
    import landsat.landsat
  File "/Users/sam/anaconda/lib/python2.7/site-packages/landsat/landsat.py", line 21, in <module>
    from image import Process, FileDoesNotExist
  File "/Users/sam/anaconda/lib/python2.7/site-packages/landsat/image.py", line 14, in <module>
    from rasterio.warp import reproject, RESAMPLING, transform
  File "/Users/sam/anaconda/lib/python2.7/site-packages/rasterio/warp.py", line 8, in <module>
    from rasterio._warp import _transform_geom, _reproject, RESAMPLING
ImportError: dlopen(/Users/sam/anaconda/lib/python2.7/site-packages/rasterio/_warp.so, 2): Symbol not found: __ZTINSt8ios_base7failureE
  Referenced from: /Users/sam/anaconda/lib/python2.7/site-packages/rasterio/_warp.so
  Expected in: dynamic lookup```

I tried @bucricket's solution:

     conda install gdal 
     conda install rasterio 
     pip install rasterio```

Without luck.

**Comment by petulla** [comment]
The way to solve this is to uninstall with brew first (with --force), then to follow the above install commands. Note this will break packages depending on your brew install.
